name: Seonhyu == Developer
description: 굴러먹을 데로 굴러먹은 그리고 구르고 있는 노땅 개발자
meta_description: "Seonhyu's blog"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://seonhyu.gihub.io'
author:         'Seonhyu'
