name: Seonhyu's Blog
description: Guides / Practices / Productivity for S/W developer
meta_description: "Seonhyu's Blog"

markdown: redcarpet
highliter: 'pygments'
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://seonhyu.gihub.io'
author:         '@seonhyu'
